name = 'Relearn'
license = 'MIT'
licenselink = 'https://github.com/McShelby/hugo-theme-relearn/blob/main/LICENSE'
description = 'A theme for Hugo designed for documentation'
homepage = 'https://github.com/McShelby/hugo-theme-relearn'
demosite = 'https://mcshelby.github.io/hugo-theme-relearn'
tags = ['dark', 'dark mode', 'docs', 'light', 'multilingual', 'responsive']
features = [
  'alerts', 'attachments', 'auto dark mode',
  'badge', 'badges', 'breadcrumbs', 'boxes', 'button', 'buttons',
  'callout', 'callouts', 'card', 'cards', 'categories', 'chemical formulae', 'chemistry', 'clipboard', 'commonmark', 'content security policy', 'copy to clipboard', 'customizable', 'color variants', 'csp',
  'dark', 'dark mode', 'diagrams', 'docs', 'documentation', 'download links',
  'expand',
  'favicon', 'file inclusion', 'file system support', 'font awesome', 'front matter cms',
  'gfm', 'github flavored markdown',
  'heading links', 'hidden pages',
  'i18n', 'icons', 'image effects', 'image resizing', 'include',
  'katex',
  'light', 'lightbox', 'link effects', 'logo', 'lunr',
  'markdown output', 'math', 'menus', 'merged table cells', 'mermaid', 'mhchem', 'mixed language search', 'multilingual', 'mobile',
  'nested menus', 'nested sections',
  'oas', 'obsidian callouts', 'offline usable', 'openapi', 'open graph',
  'pages', 'print', 'printable',
  'resources', 'responsive', 'rss', 'rtl',
  'sbom', 'schema', 'search', 'search page', 'sidebar', 'sidebar menus', 'siteparam', 'sitemap', 'social media', 'source view', 'stylesheet generator', 'subtheme', 'swagger', 'swaggerui', 'syntax highlighting',
  'table of contents', 'tables', 'tab', 'tabs', 'tags', 'task list', 'taxonomy', 'themeable', 'themes', 'toc', 'topbar buttons', 'tree list', 'twitter cards',
  'variant generator', 'versioning'
]

[module]
  [module.hugoVersion]
    min = '0.166.0'

[author]
  name = 'Sören Weber'
  homepage = 'https://github.com/McShelby'

[original]
  author = 'Mathieu Cornic'
  homepage = 'https://learn.netlify.app'
  repo = 'https://github.com/matcornic/hugo-theme-learn'
