name = 'Relearn'
license = 'MIT'
licenselink = 'https://github.com/McShelby/hugo-theme-relearn/blob/main/LICENSE'
description = 'A theme for Hugo designed for documentation'
homepage = 'https://github.com/McShelby/hugo-theme-relearn'
demosite = 'https://mcshelby.github.io/hugo-theme-relearn'
tags = ['dark', 'dark mode', 'docs', 'light', 'multilingual', 'responsive']
features = [
  'alerts',
  'badges', 'breadcrumbs', 'boxes', 'buttons',
  'callouts', 'card', 'cards', 'categories', 'chemical formulae', 'customizable', 'color variants',
  'dark', 'dark mode', 'docs', 'documentation',
  'expand',
  'favicon', 'file inclusion', 'file system support', 'font awesome', 'front matter cms',
  'gfm', 'github flavored markdown',
  'hidden pages',
  'i18n', 'icons', 'image resizing', 'include',
  'light', 'lightbox', 'logo',
  'math', 'mathjax', 'menus', 'mermaid', 'multilingual', 'mobile',
  'nested menus', 'nested sections', 'notice',
  'oas', 'offline usable', 'openapi', 'open graph',
  'print', 'printable',
  'responsive', 'rss', 'rtl',
  'schema', 'search', 'search page', 'sidebar', 'sidebar menus', 'sitemap', 'subtheme', 'swagger', 'swaggerui', 'syntax highlighting',
  'table of contents', 'tab', 'tabs', 'tags', 'task list', 'taxonomy', 'themeable', 'themes', 'toc', 'topbar buttons', 'tree list', 'twitter cards',
  'versioning'
]

[module]
  [module.hugoVersion]
    min = '0.126.3'

[author]
  name = 'Sören Weber'
  homepage = 'https://github.com/McShelby'

[original]
  author = 'Mathieu Cornic'
  homepage = 'https://learn.netlify.app'
  repo = 'https://github.com/matcornic/hugo-theme-learn'
